project:
  type: website
  resources: static

website:
  title: "kenpu.ca"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.ipynb
      - href: articles/index.qmd
        text: Articles

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true