project:
  type: website
  resources: static

website:
  title: "kenpu.ca"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.ipynb
      - href: articles/index.qmd
        text: Articles
      - about.qmd
  body-footer: "
  <div class=footer>AI Automation Group, 2024 ©</div>
  "

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    anchor-sections: true
    number-sections: true
